---
splash_sqlite_data_dir: /var/lib/splash-api
splash_sqlite_file_name: splash.sqlite
splash_sqlite_owner: root
splash_sqlite_group: root
splash_sqlite_dir_mode: "0755"
splash_sqlite_file_mode: "0644"
splash_sqlite_backup_dir: /var/backups/splash-api
splash_sqlite_backup_owner: root
splash_sqlite_backup_group: root
splash_sqlite_backup_mode: "0750"
