name: Deploy Splash Relay 
run-name: Deploy Splash Relay
on: 
  push:
    paths:
      - 'splash-relay/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: "Install & build"
        run: |
          cd splash-relay
          npm i
          npm run build
      - name: "Push to server"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          #key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          rm: true
          source: "splash-relay/package.json,splash-relay/deploy.sh,splash-relay/findusbdev.sh,splash-relay/ecosystem.config.js,splash-relay/config/*,splash-relay/dist/*,splash-relay/node_modules/*"
          strip_components: 1
          target: "~/splash/splash-relay"
      - name: "Start server"
        uses: appleboy/ssh-action@master
        with:
          debug: true
          host: ${{ secrets.SSH_HOST }}
          username: "devinrader"
          #key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            whoami
            sudo chmod +x ~/splash/splash-relay/deploy.sh
            ~/splash/splash-relay/deploy.sh