name: Deploy Splash Relay 
run-name: Deploy Splash Relay
on: 
  push:
    paths:
      - 'splash-relay/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: "Install & build"
        run: |
          cd splash-relay
          npm i
          npm run build
      - name: "Push to server"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          #key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          rm: true
          source: "splash-relay/deploy.sh,splash-relay/ecosystem.config.js,splash-relay/dist/*"
          strip_components: 1
          target: "~/splash/splash-relay"
      - name: "Start server"
        uses: appleboy/ssh-action@master
        with:
          debug: true
          host: ${{ secrets.SSH_HOST }}
          username: "devinrader"
          #key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Running as user"
            whoami

            echo "Checking node.js installation"
            if which node >/dev/null
              then
                echo "node.js installation found"
              else
                echo "node.js installation not found. Install node.js and npm."
                sudo apt install -y ca-certificates curl gnupg
                curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/nodesource.gpg
                NODE_MAJOR=20
                echo "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
                sudo apt update
                sudo apt install nodejs
                node -v
              fi

            mkdir -p /opt/splash/splash-relay
            cp ~/splash/splash-relay/ /opt/splash/splash-relay

            npm install pm2@latest -g
            pm2 update
            pm2 start /opt/splash/splash-relay/ecosystem.config.js
            pm2 save


      # (optional - only needed if your config uses environment variables)
      # - name: Create env file
      #   run: |
      #     touch .env
      #     echo SPLASH_SERVER_ADDRESS=${{ secrets.SPLASH_SERVER_ADDRESS }} >> .env

      # - name: Install PM2
      #   run: npm i pm2 -g

      # - name: Deploy
      #   run: env $(cat .env | grep -v \"#\" | xargs) pm2 deploy splash-relay/ecosystem.config.js production setup
        # Or alternately, put this deploy script in your package.json's scripts and run it using yarn/npm:
        # run: yarn deploy

# jobs:
      #
      # ... your other steps, such as running tests, etc...
      #
      # - name: Set up SSH
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy.key
      #     sudo chmod 600 ~/.ssh/deploy.key
      #     echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      #   shell: bash
      #   env:
      #     SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      #     SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

#   Explore-Gitea-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
#       - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
#       - run: echo "🔎 The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v4
#       - run: echo "💡 The ${{ gitea.repository }} repository has been cloned to the runner."
#       - run: echo "🖥️ The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ gitea.workspace }}
#       - run: echo "🍏 This job's status is ${{ job.status }}."