CREATE TABLE IF NOT EXISTS chlorinator_profiles (
  pool_id TEXT PRIMARY KEY,
  profile_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
