---
splash_serial_package_state: present
splash_serial_package_arch: armhf
# splash_serial_package_version: "0.0.0~main.20260328002517+9d25f97"

splash_serial_env:
  NATS_URL: nats://splash-core.local:4222
  SERIAL_DEVICE: /dev/ttyUSB0
  SERIAL_RECONNECT_INTERVAL_MS: "10000"
  SERIAL_WRITE_TIMEOUT_MS: "2000"
  SERIAL_HTTP_BIND: 127.0.0.1:9108
  SERIAL_DEFAULT_IDLE_MS: "50"
  LOG_LEVEL: info
  TZ: America/New_York
