FROM node:latest

# RUN mkdir -p /home/node/splash/splash-relay/node_modules && chown -R node:node /home/node/splash/splash-relay
USER node

WORKDIR /home/node/splash/splash-relay

RUN ls
RUN pwd
RUN echo "$PWD"
RUN pwd && ls
RUN ls ..

COPY --chown=node:node splash-relay/package*.json .

RUN npm install

COPY --chown=node:node . .

EXPOSE 8080

CMD [ "npm", "start" ]