FROM node:22-alpine

USER node

WORKDIR /home/node/splash/splash-relay

COPY --chown=node:node splash-relay/package*.json .

RUN npm install

COPY --chown=node:node splash-relay/. .

EXPOSE 8080

CMD [ "npm", "start" ]